url: "https://dadangeuy.github.io"
baseurl: ""
title: rizaldi.dev
author: Irsyad Rizaldi
email: irsyad.rizaldi97@gmail.com
description: ğŸ’–, ï¸ğŸ›µ & ğŸ‘¨â€ğŸ’»
github_username: "dadangeuy"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
