title: rizaldi.dev
email: irsyad.rizaldi97@gmail.com
description: ğŸ’–, ï¸ğŸ›µ & ğŸ‘¨â€ğŸ’»
url: "https://dadangeuy.github.io"
baseurl: ""

plugins:
  - jekyll-feed

theme: minima
minima:
  skin: dark
  social_links:
    github: dadangeuy
    linkedin: dadangeuy
author:
  name: Irsyad Rizaldi
  email: irsyad.rizaldi97@gmail.com
